#!/bin/bash -x

PLUG_IN_LIST="monitor controlflow"
NIGHTLY_MASTER_PLUG_IN_VERSION="2.$(expr $MIDDLE_STABLE + 1)-SNAPSHOT"
NIGHTLY_STABLE_PLUG_IN_VERSION="2.$MIDDLE_STABLE-SNAPSHOT"
NIGHTLY_MAINT_PLUG_IN_VERSION="2.$(expr $MIDDLE_STABLE - 1)-SNAPSHOT"
echo $NIGHTLY_MASTER_PLUG_IN_VERSION
echo $NIGHTLY_STABLE_PLUG_IN_VERSION
echo $NIGHTLY_MAINT_PLUG_IN_VERSION
for NIGHTLY_VERSION in $NIGHTLY_MASTER_VERSION $NIGHTLY_STABLE_VERSION $NIGHTLY_MAINT_VERSION; do
  declare -a PLUG_IN_URLS
  NIGHTLY_URL="https://build.geoserver.org/geoserver/$NIGHTLY_VERSION/geoserver-$NIGHTLY_VERSION-latest-war.zip"
  [[ "$NIGHTLY_MASTER_VERSION" == *"$NIGHTLY_VERSION"* ]] && PLUG_IN_VERSION="$NIGHTLY_MASTER_PLUG_IN_VERSION"
  [[ "$NIGHTLY_STABLE_VERSION" == *"$NIGHTLY_VERSION"* ]] && PLUG_IN_VERSION="$NIGHTLY_STABLE_PLUG_IN_VERSION"
  [[ "$NIGHTLY_MAINT_VERSION" == *"$NIGHTLY_VERSION"* ]] && PLUG_IN_VERSION="$NIGHTLY_MAINT_PLUG_IN_VERSION"
  echo $PLUG_IN_VERSION
  for PLUG_IN_NAME in $PLUG_IN_LIST; do
    echo $PLUG_IN_NAME
    echo $PLUG_IN_VERSION
    URL="https://build.geoserver.org/geoserver/$NIGHTLY_VERSION/ext-latest/geoserver-$PLUG_IN_VERSION-$PLUG_IN_NAME-plugin.zip"
    echo "Plugin $PLUG_IN_NAME URL for version $PLUG_IN_VERSION: $URL"
    PLUG_IN_URLS+=($URL)
  done
  echo "${PLUG_IN_URLS=[@]}" 
  docker build \
    --build-arg GEOSERVER_WEBAPP_SRC=$NIGHTLY_URL \
    --build-arg PLUG_IN_URLS=${PLUG_IN_URLS=[@]} \
    -f $DOCKERFILE_PATH \
    -t "${DOCKER_REPO}:test-$NIGHTLY_VERSION" .
done

for VERSION in "$STABLE_VERSION $MAINT_VERSION"; do 
  URL="https://netcologne.dl.sourceforge.net/project/geoserver/GeoServer/$VERSION/geoserver-$VERSION-war.zip"
  for PLUG_IN_NAME in "$PLUG_IN_LIST"; do
    PLUG_IN_URLS+=(https://netcologne.dl.sourceforge.net/project/geoserver/GeoServer/$VERSION/ext-latest/geoserver-${VERSION}-${PLUG_IN_NAME}-plugin.zip)
  done
  echo "${PLUG_IN_URLS=[@]}" 
  docker build \
    --build-arg GEOSERVER_WEBAPP_SRC=$URL \
    --build-arg PLUG_IN_URLS=${PLUG_IN_URLS=[@]} \
    -f $DOCKERFILE_PATH \
    -t "${DOCKER_REPO}:test-$VERSION" .
done

